# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x86
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x86)
  SGL_config = debug_x86
  TestProject_config = debug_x86
endif
ifeq ($(config),debug_x86_64)
  SGL_config = debug_x86_64
  TestProject_config = debug_x86_64
endif
ifeq ($(config),release_x86)
  SGL_config = release_x86
  TestProject_config = release_x86
endif
ifeq ($(config),release_x86_64)
  SGL_config = release_x86_64
  TestProject_config = release_x86_64
endif

PROJECTS := SGL TestProject

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

SGL:
ifneq (,$(SGL_config))
	@echo "==== Building SGL ($(SGL_config)) ===="
	@${MAKE} --no-print-directory -C SGL -f Makefile config=$(SGL_config)
endif

TestProject: SGL
ifneq (,$(TestProject_config))
	@echo "==== Building TestProject ($(TestProject_config)) ===="
	@${MAKE} --no-print-directory -C TestProject -f Makefile config=$(TestProject_config)
endif

clean:
	@${MAKE} --no-print-directory -C SGL -f Makefile clean
	@${MAKE} --no-print-directory -C TestProject -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x86"
	@echo "  debug_x86_64"
	@echo "  release_x86"
	@echo "  release_x86_64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   SGL"
	@echo "   TestProject"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"